/**
 * @file src/utils/AuthContext.jsx
 * @description Global Authentication Provider for the React Frontend.
 * Manages the Admin's login state and securely stores the temporary HTTP upload token
 * required to bypass WebSocket limitations when transferring large asset files.
 * Utilizes sessionStorage to ensure authentication persists across browser refreshes
 * but is safely destroyed when the tab is closed.
 */
import React, { createContext, useState, useContext, useEffect } from 'react';

const AuthContext = createContext();

export const AuthProvider = ({ children }) => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [uploadToken, setUploadToken] = useState(null);

  useEffect(() => {
    // Intercept component mount to restore session state from browser memory
    const authFlag = sessionStorage.getItem('isAdminAuthenticated');
    const savedToken = sessionStorage.getItem('adminUploadToken');
    
    if (authFlag === 'true') {
      setIsAuthenticated(true);
      if (savedToken) setUploadToken(savedToken);
    }
  }, []);

  /**
   * Authenticates the user session and caches the HTTP bridge token.
   * @param {string} token - The 256-bit hex token generated by the backend.
   */
  const login = (token) => {
    setIsAuthenticated(true);
    setUploadToken(token);
    sessionStorage.setItem('isAdminAuthenticated', 'true');
    if (token) sessionStorage.setItem('adminUploadToken', token);
  };

  /**
   * Destroys the user session and clears sensitive data from browser memory.
   */
  const logout = () => {
    setIsAuthenticated(false);
    setUploadToken(null);
    sessionStorage.removeItem('isAdminAuthenticated');
    sessionStorage.removeItem('adminUploadToken');
  };

  return (
    <AuthContext.Provider value={{ isAuthenticated, uploadToken, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => useContext(AuthContext);